set number relativenumber
syntax on
set clipboard=unnamed
set encoding=UTF-8
set shiftwidth=4
set autoindent
set smartindent
set tabstop=4
set softtabstop=4
set hlsearch
set smarttab
set complete-=i
set laststatus=2
set ruler
set wildmenu

if !&scrolloff
  set scrolloff=1
endif
if !&sidescrolloff
  set sidescrolloff=5
endif
set display+=lastline


if &listchars ==# 'eol:$'
  set listchars=tab:>\ ,trail:-,extends:>,precedes:<,nbsp:+
endif

highlight LineNr term=bold cterm=NONE ctermfg=NONE ctermbg=DarkGrey 
highlight CursorLine cterm=NONE ctermbg=darkgrey ctermfg=NONE guibg=darkred guifg=white
"highlight CursorColumn cterm=NONE ctermbg=darkred ctermfg=NONE guibg=darkred guifg=white
set cursorline
"set background=dark termguicolors cursorline

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plugin 'junegunn/fzf.vim'
call vundle#end()            " required
filetype plugin indent on    " required

"Airline configs
let g:airline#extensions#tabline#left_sep = ' '
let g:airline_powerline_fonts = 0
let g:airline#extensions#tabline#left_alt_sep = '|'
let g:airline#extensions#tabline#formatter = 'simple'

"fzf configs
let g:fzf_preview_window = ''
let g:fzf_preview_window = 'right:50%'

set laststatus=0
